# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DyamkDemoApp' do
  
  inhibit_all_warnings!
  pod 'DyamkClient', :path => '../DyamkClient.podspec'

end
